export const FETCH_APPLICATIONCOUNT_REQUEST = 'FETCH_APPLICATIONCOUNT_REQUEST';
export const FETCH_APPLICATIONCOUNT_SUCCESS = 'FETCH_APPLICATIONCOUNT_SUCCESS';
export const FETCH_APPLICATIONCOUNT_FAILURE = 'FETCH_APPLICATIONCOUNT_FAILURE';

export const FETCH_GENERATETABLE_REQUEST = 'FETCH_GENERATETABLE_REQUEST';
export const FETCH_GENERATETABLE_SUCCESS = 'FETCH_GENERATETABLE_SUCCESS';
export const FETCH_GENERATETABLE_FAILURE = 'FETCH_GENERATETABLE_FAILURE';

export const FETCH_STUDENTBYID_REQUEST = 'FETCH_STUDENTBYID_REQUEST';
export const FETCH_STUDENTBYID_SUCCESS = 'FETCH_STUDENTBYID_SUCCESS';
export const FETCH_STUDENTBYID_FAILURE = 'FETCH_STUDENTBYID_FAILURE';

export const FETCH_DOCUMENTTABLE_REQUEST = 'FETCH_DOCUMENTTABLE_REQUEST';
export const FETCH_DOCUMENTTABLE_SUCCESS = 'FETCH_DOCUMENTTABLE_SUCCESS';
export const FETCH_DOCUMENTTABLE_FAILURE = 'FETCH_DOCUMENTTABLE_FAILURE';

export const FETCH_ADMISSIONSUBMITGPA_REQUEST = 'FETCH_ADMISSIONSUBMITGPA_REQUEST';
export const FETCH_ADMISSIONSUBMITGPA_SUCCESS = 'FETCH_ADMISSIONSUBMITGPA_SUCCESS';
export const FETCH_ADMISSIONSUBMITGPA_FAILURE = 'FETCH_ADMISSIONSUBMITGPA_FAILURE';

export const FETCH_STUDENTGPA_REQUEST = 'FETCH_STUDENTGPA_REQUEST';
export const FETCH_STUDENTGPA_SUCCESS = 'FETCH_STUDENTGPA_SUCCESS';
export const FETCH_STUDENTGPA_FAILURE = 'FETCH_STUDENTGPA_FAILURE';