export const FETCH_APPLICATIONCOUNT_REQUEST = 'FETCH_APPLICATIONCOUNT_REQUEST';
export const FETCH_APPLICATIONCOUNT_SUCCESS = 'FETCH_APPLICATIONCOUNT_SUCCESS';
export const FETCH_APPLICATIONCOUNT_FAILURE = 'FETCH_APPLICATIONCOUNT_FAILURE';

export const FETCH_GENERATETABLE_REQUEST = 'FETCH_GENERATETABLE_REQUEST';
export const FETCH_GENERATETABLE_SUCCESS = 'FETCH_GENERATETABLE_SUCCESS';
export const FETCH_GENERATETABLE_FAILURE = 'FETCH_GENERATETABLE_FAILURE';

export const FETCH_STUDENTBYID_REQUEST = 'FETCH_STUDENTBYID_REQUEST';
export const FETCH_STUDENTBYID_SUCCESS = 'FETCH_STUDENTBYID_SUCCESS';
export const FETCH_STUDENTBYID_FAILURE = 'FETCH_STUDENTBYID_FAILURE';