export const FETCH_APPLICANTSTATUS_REQUEST = 'FETCH_APPLICANTSTATUS_REQUEST';
export const FETCH_APPLICANTSTATUS_SUCCESS = 'FETCH_APPLICANTSTATUS_SUCCESS';
export const FETCH_APPLICANTSTATUS_FAILURE = 'FETCH_APPLICANTSTATUS_FAILURE';