// ActionType.js
export const FETCH_CAMPUS_REQUEST = 'FETCH_CAMPUS_REQUEST';
export const FETCH_CAMPUS_SUCCESS = 'FETCH_CAMPUS_SUCCESS';
export const FETCH_CAMPUS_FAILURE = 'FETCH_CAMPUS_FAILURE';

export const FETCH_DIVISION_REQUEST = 'FETCH_DIVISION_REQUEST';
export const FETCH_DIVISION_SUCCESS = 'FETCH_DIVISION_SUCCESS';
export const FETCH_DIVISION_FAILURE = 'FETCH_DIVISION_FAILURE';

export const FETCH_LEVEL_REQUEST = 'FETCH_LEVEL_REQUEST';
export const FETCH_LEVEL_SUCCESS = 'FETCH_LEVEL_SUCCESS';
export const FETCH_LEVEL_FAILURE = 'FETCH_LEVEL_FAILURE';

export const FETCH_STRAND_REQUEST = 'FETCH_STRAND_REQUEST';
export const FETCH_STRAND_SUCCESS = 'FETCH_STRAND_SUCCESS';
export const FETCH_STRAND_FAILURE = 'FETCH_STRAND_FAILURE';

export const FETCH_NATIONALITY_REQUEST = 'FETCH_NATIONALITY_REQUEST';
export const FETCH_NATIONALITY_SUCCESS = 'FETCH_NATIONALITY_SUCCESS';
export const FETCH_NATIONALITY_FAILURE = 'FETCH_NATIONALITY_FAILURE';

export const FETCH_RELIGION_REQUEST = 'FETCH_RELIGION_REQUEST';
export const FETCH_RELIGION_SUCCESS = 'FETCH_RELIGION_SUCCESS';
export const FETCH_RELIGION_FAILURE = 'FETCH_RELIGION_FAILURE';

export const FETCH_PROVINCE_REQUEST = 'FETCH_PROVINCE_REQUEST';
export const FETCH_PROVINCE_SUCCESS = 'FETCH_PROVINCE_SUCCESS';
export const FETCH_PROVINCE_FAILURE = 'FETCH_PROVINCE_FAILURE';

export const FETCH_MUNICIPALITY_REQUEST = 'FETCH_MUNICIPALITY_REQUEST';
export const FETCH_MUNICIPALITY_SUCCESS = 'FETCH_MUNICIPALITY_SUCCESS';
export const FETCH_MUNICIPALITY_FAILURE = 'FETCH_MUNICIPALITY_FAILURE';

export const FETCH_BARANGAY_REQUEST = 'FETCH_BARANGAY_REQUEST';
export const FETCH_BARANGAY_SUCCESS = 'FETCH_BARANGAY_SUCCESS';
export const FETCH_BARANGAY_FAILURE = 'FETCH_BARANGAY_FAILURE';

export const FETCH_ONLINEAPPLICATIONFORM_REQUEST = 'FETCH_ONLINEAPPLICATIONFORM_REQUEST';
export const FETCH_ONLINEAPPLICATIONFORM_SUCCESS = 'FETCH_ONLINEAPPLICATIONFORM_SUCCESS';
export const FETCH_ONLINEAPPLICATIONFORM_FAILURE = 'FETCH_ONLINEAPPLICATIONFORM_FAILURE';